name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  jiraBaseUrl:
    description: Jira base url
    required: true
  jiraEmail:
    description: Jira email
    required: true
  jiraToken:
    description: Jira token
    required: true
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    required: true
  owner:
    description: 'The owner'
  repository:
    description: 'The github project'
outputs:
  result: # just a string
    description: 'A simple ok'
runs:
  using: 'node12'
  main: 'index.js'
